[package]
name = "pingapi"
version = "0.1.0"
authors = ["Yasamato <agent77326@gmail.com>"]
edition = "2018"
repository = "https://github.com/ranimepiracy/pingapi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-cors = "0.5.4"
env_logger = "0.8.3"
futures = "0.3.13"
log = "0.4.14"
redis = "0.20.0"
reqwest = "0.11.2"
serde = "1.0.125"
